#ifndef TOP14_LIBRARY_GLOBAL_H
#define TOP14_LIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOP14_LIBRARY_LIBRARY)
#  define TOP14_LIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TOP14_LIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TOP14_LIBRARY_GLOBAL_H
